version: "2.4"
services:
  rabbitmq:
    image: rabbitmq:3.8.0-management-alpine
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: nc -z localhost 5672 || exit -1
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s

  publisher:
    image: acme/test-publisher-async:1.0
    build: 
      context: .
      dockerfile: docker/Dockerfile-async-publisher
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      RABBIT_HOST: rabbitmq
      RABBIT_PUBLISHER_CONFIRM: "true"
      RABBIT_TIMEOUT: 10
    command: dotnet run 

  consumer:
    image: acme/test-consumer-async:1.0
    build: 
      context: .
      dockerfile: docker/Dockerfile-async-consumer
    depends_on:
      rabbitmq:
        condition: service_healthy
    command: dotnet run 
    